import localFont from "next/font/local";
import { DynaPuff } from "@next/font/google";
import "./globals.css";
import Navbar from "./components/navbar"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});  

// const dynaPuff = DynaPuff({ subsets: ['latin'], weight: ['400', '700'] });

const dynaPuff = DynaPuff({ subsets: ['latin'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dynaPuff.className} antialiased`}
      >
        <Navbar/>
        {children}
        
      </body>
    </html>
  );
}
